"""empty message

Revision ID: 6b6cf96b2907
Revises: d58133d14a2c
Create Date: 2021-06-02 21:23:04.332898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6cf96b2907'
down_revision = 'd58133d14a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'skincare_step',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'skincare_step',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
